# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "down", require: false
gem "amazing_print", require: false
gem "ougai", require: false

# Fix: https://github.com/rubyzip/rubyzip/pull/374
gem "rubyzip", require: false, github: "miry/rubyzip", branch: "enable-frozen-builds"

gem "minitest", require: false
gem "rake", require: false
gem "simplecov", require: false

gem "standard", require: false
