# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Fix: https://github.com/awesome-print/awesome_print/pull/345
gem 'awesome_print', require: false, github: 'awesome-print/awesome_print'
gem 'down', require: false
gem 'ougai', require: false

# Fix: https://github.com/rubyzip/rubyzip/pull/374
gem 'rubyzip', require: false, github: 'miry/rubyzip', branch: 'enable-frozen-builds'

gem 'minitest', require: false
gem 'rake', require: false
gem 'simplecov', require: false

gem 'rubocop', require: false
